export function getElements(doc = document) {
  return {
    topicList: doc.getElementById("topicList"),
    topicInput: doc.getElementById("topic"),
    constraintsInput: doc.getElementById("constraints"),
    apiKeyInput: doc.getElementById("apiKey"),
    modelNameInput: doc.getElementById("modelName"),
    baseUrlInput: doc.getElementById("baseUrl"),
    numEpisodesInput: doc.getElementById("numEpisodes"),
    maxIterationsInput: doc.getElementById("maxIterations"),
    useMockInput: doc.getElementById("useMock"),
    apiKeyHint: doc.getElementById("apiKeyHint"),
    status: doc.getElementById("status"),
    statusActions: doc.getElementById("statusActions"),
    jobSnapshot: doc.getElementById("jobSnapshot"),
    debugStatus: doc.getElementById("debugStatus"),
    result: doc.getElementById("result"),
    progress: doc.getElementById("progress"),
    preview: doc.getElementById("preview"),
    diagnostics: doc.getElementById("diagnostics"),
    historyList: doc.getElementById("historyList"),
    historySummary: doc.getElementById("historySummary"),
    historyPageInfo: doc.getElementById("historyPageInfo"),
    historySearchInput: doc.getElementById("historySearchInput"),
    historySortSelect: doc.getElementById("historySortSelect"),
    undoBanner: doc.getElementById("undoBanner"),
    saveConfigBtn: doc.getElementById("saveConfigBtn"),
    testModelBtn: doc.getElementById("testModelBtn"),
    generateBtn: doc.getElementById("generateBtn"),
    refreshHistoryBtn: doc.getElementById("refreshHistoryBtn"),
    searchHistoryBtn: doc.getElementById("searchHistoryBtn"),
    clearHistorySearchBtn: doc.getElementById("clearHistorySearchBtn"),
    prevHistoryBtn: doc.getElementById("prevHistoryBtn"),
    nextHistoryBtn: doc.getElementById("nextHistoryBtn"),
  };
}
